### ISSUE TITLE
Phase 2.2: Build messages array from session transcripts in gateway

### ISSUE THREAD

**Issue by rookdaemon** [rookdaemon/daemon-engine#81]
## Overview

Refactor `gateway.ts` to construct the full messages array from session JSONL transcripts before each LLM call. This makes context reconstruction explicit and deterministic.

## Background

Currently, gateway.ts relies on Claude CLI session continuation for conversation context. After Phase 1 removes `--continue`, we need explicit context reconstruction.

The session store already maintains JSONL transcripts at `state/sessions/{sessionKey}/transcript.jsonl`. Each line is a `SessionMessage`:
```typescript
interface SessionMessage {
  role: "user" | "assistant" | "tool";
  content: string | null;
  toolCalls?: ToolCall[];
  toolCallId?: string;
  timestamp: number;
}
```

### Files to Modify

1. **`src/gateway.ts`**
   - In `processMessage()` and `processMessageStream()`:
     1. Load full transcript from session store
     2. Convert `SessionMessage[]` to `Message[]`
     3. Prepend system prompt message
     4. Pass to `callClaude()`
   
   ```typescript
   // Current flow:
   const existingClaudeSessionId = metadata?.claudeSessionId;
   claudeResponse = await callClaude({
     prompt: message,
     systemPrompt: freshSystemPrompt || "",
     continueSession: continueSessionId,
   });
   
   // New flow:
   const transcript = await this.context.sessionStore.load(sessionKey);
   const messages = this.buildMessagesArray(transcript, userMessage);
   claudeResponse = await callClaude({
     messages,
     systemPrompt: systemPrompt,
   });
   ```

2. **`src/gateway.ts`** (new methods)
   - `buildMessagesArray(transcript: SessionMessage[], current: string): Message[]`
   - `convertSessionToMessage(sm: SessionMessage): Message | null`

3. **`src/workspace.ts`**
   - Ensure `buildSystemPromptWithEnv()` returns complete system context:
     - SOUL.md
     - AGENTS.md (already included)
     - USER.md (already included)
     - MEMORY.md (already included)
     - TOOLS.md (already included)
     - HEARTBEAT.md (already included)

### Test Updates Required

4. **`test/gateway.test.ts`**
   - Add tests for `buildMessagesArray()`
   - Verify complete transcript is loaded for each call
   - Test empty transcript handling
   - Test large transcript handling

## Acceptance Criteria

- [ ] Every LLM call receives full conversation history
- [ ] System prompt is always `messages[0]` (or passed separately per Claude CLI interface)
- [ ] Session transcripts are the sole source of conversation history
- [ ] No reliance on Claude-side session state
- [ ] Replaying same JSONL produces identical LLM input

## Dependencies

- Phase 1: Remove `--continue` path (issue #79)
- Phase 2.1: Change `callClaude()` interface (issue #80)

## Notes

This phase does NOT implement compaction. If transcripts grow too large, the LLM call will fail with context overflow. Phase 3 addresses this with compaction.

Consider: Should tool messages be included in the reconstructed context? They provide important context about what actions were taken, but also add token overhead.
